on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: abhisheaacr.azurecr.io
        username: ${{ secrets.acr_abhisheaAcr_username }}
        password: ${{ secrets.acr_abhisheaAcr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/app-dir/WindowsMvcApp" -f  "app-dir/WindowsMvcApp/Dockerfile" -t abhisheaacr.azurecr.io/jamindaaks2438c:${{ github.sha }}
        docker push abhisheaacr.azurecr.io/jamindaaks2438c:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_jaminda-aks-2_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep jamindaaks281b1 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace jamindaaks281b1`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: jamindaaks281b1
        container-registry-url: abhisheaacr.azurecr.io
        container-registry-username: ${{ secrets.acr_abhisheaAcr_username }}
        container-registry-password: ${{ secrets.acr_abhisheaAcr_password }}
        secret-name: jamindaaks2dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: jamindaaks281b1
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          abhisheaacr.azurecr.io/jamindaaks2438c:${{ github.sha }}
        imagepullsecrets: |
          jamindaaks2dockerauth